# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Github Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
    - name: uv-setup
      # Install a specific uv version using the installer
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: "Set up Python"
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"
    - name: Install dependencies
      run: uv sync --all-extras --dev
    - name: Ruff
      uses: chartboost/ruff-action@v1
    - name: Test with pytest
      run: uv run pytest tests
    - name: Build a binary wheel and a source tarball
      run: uv build
    - name: Prep for mkdocs
      run: uv pip compile pyproject.toml -o requirements_docs.txt --group mkdocs
    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REQUIREMENTS: requirements_docs.txt
        CUSTOM_DOMAIN: updates2mqtt.rhizomatics.org.uk



